### ISSUE TITLE
Can't get or build go package

### ISSUE THREAD

**Issue by mxp1l0t** [jaxxstorm/like-my-friend#7]
Seems to be an issue with a dependent package but I'm not sure how to fix this.
Package https://github.com/ahmdrz/goinsta

go get github.com/jaxxstorm/like-my-friend
# github.com/jaxxstorm/like-my-friend/cmd
src\github.com\jaxxstorm\like-my-friend\cmd\root.go:75:23: insta.GetUserByUsername undefined (type *goinsta.Instagram has no field or method GetUserByUsername)
src\github.com\jaxxstorm\like-my-friend\cmd\root.go:86:21: insta.LatestUserFeed undefined (type *goinsta.Instagram has no field or method LatestUserFeed)
src\github.com\jaxxstorm\like-my-friend\cmd\root.go:97:21: insta.Like undefined (type *goinsta.Instagram has no field or method Like)

go build github.com/jaxxstorm/like-my-friend
# github.com/jaxxstorm/like-my-friend/cmd
src\github.com\jaxxstorm\like-my-friend\cmd\root.go:75:23: insta.GetUserByUsername undefined (type *goinsta.Instagram has no field or method GetUserByUsername)
src\github.com\jaxxstorm\like-my-friend\cmd\root.go:86:21: insta.LatestUserFeed undefined (type *goinsta.Instagram has no field or method LatestUserFeed)
src\github.com\jaxxstorm\like-my-friend\cmd\root.go:97:21: insta.Like undefined (type *goinsta.Instagram has no field or method Like)

**Comment by jaxxstorm** [comment]
Yes, it seems that the dependent library changed. This project used [Glide](https://glide.sh/) for its deps, so if you do `glide install` from a cloned repo  in your `$GOPATH` it should build a working version of the libs.
