### ISSUE TITLE
Liking only the last photo

### ISSUE THREAD

**Issue by mxp1l0t** [jaxxstorm/like-my-friend#8]
How would I change the program to only like the latest photo from a user (LatestUserFeed) instead of the first 18 photos from a user?
Is there a sample config file that might have these options?

I really appreciate the help.  Thank you.

**Comment by jaxxstorm** [comment]
I've added this feature in v0.2. You can download it from here https://github.com/jaxxstorm/like-my-friend/releases/tag/v0.2

Specify the `-P flag` and it'll only like the last X photos, example:

```
like-my-friend -u <username> -p <password> -a <my_friend> -P 3
```
